title: Libera Chat
description: A next-generation IRC network for FOSS projects collaboration!
baseurl: ""
url: https://libera.chat

mastodon:
  username: liberachat
  instance: fosstodon.org
irc:
  plaintext:
    name: irc.libera.chat:6667 (plaintext)
    link: irc://irc.libera.chat:6667
  tls:
    name: irc.libera.chat:6697 (TLS)
    link: ircs://irc.libera.chat:6697

collections_dir: content

permalink: /:name

collections:
  guides:
    output: true
    permalink: /:collection/:name
  posts:
    output: true
    permalink: /news/:title

feed:
  path: atom.xml

defaults:
  - scope:
      path: ""
      type: guides
    values:
      layout: guides
  - scope:
      path: ""
      type: posts
    values:
      layout: article
  - scope:
      path: ""
    values:
      layout: default

locale: en_GB

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .well-known
